server:
  port: 8088
spring:
  application:
    name: cloud-gateway
  main:
    web-application-type: reactive
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        username: ${spring.cloud.nacos.username}
        password: ${spring.cloud.nacos.password}
    gateway:
      routes:
        - id: deny-inner
          uri: no://op
          order: -1
          predicates:
            - Path=/*/inner/**
          filters:
            - SetStatus=404
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      # 白名单（无需登录）
      auth:
        white-list:
          - /*/auth/login
          - /*/auth/parseToken
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s