spring:
  application:
    name: cloud-order
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      # nacos配置中心
      config:
        group: DEFAULT_GROUP
        namespace: public
        file-extension: yaml
      # nacos服务注册发现
      discovery:
        group: DEFAULT_GROUP
        namespace: public
  #引入nacos配置
  config:
    import:
      - nacos:common.yaml?refreshEnabled=true
      - nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}?refreshEnabled=true

